language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      language: generic

install:
  - pip install --upgrade pip
  - pip install -U -r python/requirements.txt

script:
  - cd python && python setup.py develop test
